config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  get "/home", to: "static_pages#home", as: "home"
  get "/help", to: "static_pages#help", as: "help"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: :edit
  resources :password_resets, except: %i(new create edit update)
  resources :microposts, only: %i(create destroy)
  resources :relationships, only: %i(create destroy)

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "the_form_contains" %>
      <%= t("error_param", count: object.errors) %>
    </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items%>
  </ol>
  <%= will_paginate @feed_items, params: { controller: :static_pages, action: :home } %>
<% end %>

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("text_sample"), home_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("text_home"), home_path %></li>
        <li><%= link_to t("text_help"), help_path %></li>
        <li><%= link_to t("text_signup"), new_user_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("text_loggin"), login_path %></li>
          <li class="dropdown">
          <%= link_to "#", class: "dropdown-toggle",
            data: {toggle: "dropdown"} do %>
            <%= t "text_account" %>
            <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to t("text_profile"), current_user %></li>
            <li><%= link_to t("text_settings"), edit_user_path(current_user) %></li>
            <li><%= link_to "Users", users_path %></li>
            <li class="divider"></li>
            <li>
              <%= link_to t("text_logout"), logout_path, method: :delete %>
            </li>
          </ul>
        <% else %>
          <li><%= link_to t("text_loggin"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost  do |f| %>
<%= render "shared/error_messages", object: f.object %>
<div class="field">
  <%= f.text_area :content, placeholder: t("microposts.text_micropost_textarea") %>
</div>
<%= f.submit t("microposts.text_micropost_post"), class: "btn btn-primary" %>
<span class="image">
  <%= f.file_field :image, accept: Settings.file_valid %>
</span>
<% end %>
<%= javascript_pack_tag "custom", "data-turbolinks-track": "reload" %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <%= t "follow.text_following" %>
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="follower" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= t "follow.text_followers" %>
  </a>
</div>

app/views/shared/_user.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t("microposts.text_micropost_feed"), current_user %></span>
<span><%= pluralize(current_user.microposts.count, t("microposts.text_micropost_name")) %></span>